name:                backend
version:             0.1.0.0
github:              owner/backend
license:             BSD-3-Clause
author:              Project Owner
maintainer:          dev@example.com
copyright:           Project Owner

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/owner/backend#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
library:
  source-dirs: src

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - backend
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  backend-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - backend
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
